// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopfloorManager.Infrastructure.Data;

#nullable disable

namespace ShopfloorManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ShopfloorDbContext))]
    partial class ShopfloorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("LoggedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_in_at");

                    b.Property<DateTimeOffset?>("LoggedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_out_at");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Administration"
                        },
                        new
                        {
                            Id = 2,
                            Code = "QC",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Quality Control"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PROD",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Production"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ENG",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Dimension", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BalloonNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("balloon_number");

                    b.Property<decimal?>("BalloonSort")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("balloon_sort");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<bool>("IsTextType")
                        .HasColumnType("boolean")
                        .HasColumnName("is_text_type");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("min_value");

                    b.Property<string>("NominalText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nominal_text");

                    b.Property<decimal?>("NominalValue")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("nominal_value");

                    b.Property<int>("PartOpId")
                        .HasColumnType("integer")
                        .HasColumnName("part_op_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal?>("ToleranceMinus")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("tolerance_minus");

                    b.Property<decimal?>("TolerancePlus")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("tolerance_plus");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("mm")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_dimensions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_dimensions_category_id");

                    b.HasIndex("PartOpId", "BalloonNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_dimensions_part_op_id_balloon_number");

                    b.ToTable("dimensions", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.DimensionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dimension_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_dimension_categories_code");

                    b.ToTable("dimension_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LIN",
                            Description = "Thước cặp, panme",
                            Name = "Linear"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ANG",
                            Description = "Thước góc",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 3,
                            Code = "THD",
                            Description = "Dưỡng ren, ring gauge",
                            Name = "Thread"
                        },
                        new
                        {
                            Id = 4,
                            Code = "GEO",
                            Description = "CMM, dial indicator",
                            Name = "Geometric"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SFC",
                            Description = "Surface tester",
                            Name = "Surface"
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Folder")
                        .HasColumnType("text")
                        .HasColumnName("folder");

                    b.Property<bool>("IsGcode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gcode");

                    b.Property<bool>("IsJobNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("is_job_number");

                    b.Property<bool>("IsOpNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("is_op_number");

                    b.Property<bool>("IsPartNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("is_part_number");

                    b.Property<bool>("IsRevision")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revision");

                    b.Property<bool>("IsSegment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_segment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_file_types");

                    b.ToTable("file_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DRW",
                            Folder = "drawings",
                            IsGcode = false,
                            IsJobNumber = false,
                            IsOpNumber = false,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "Drawing",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "GCD",
                            Folder = "gcodes",
                            IsGcode = true,
                            IsJobNumber = true,
                            IsOpNumber = true,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = true,
                            Name = "G-Code",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "RTC",
                            Folder = "routecards",
                            IsGcode = false,
                            IsJobNumber = true,
                            IsOpNumber = true,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "Route Card",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "FXT",
                            Folder = "fixtures",
                            IsGcode = false,
                            IsJobNumber = true,
                            IsOpNumber = true,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "Fixture Drawing",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "THD",
                            Folder = "threads",
                            IsGcode = false,
                            IsJobNumber = false,
                            IsOpNumber = true,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "Thread Drawing",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "TLS",
                            Folder = "tools",
                            IsGcode = false,
                            IsJobNumber = false,
                            IsOpNumber = true,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "Tool List",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "CAM",
                            Folder = "cam",
                            IsGcode = false,
                            IsJobNumber = false,
                            IsOpNumber = true,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "CAM File",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "CAD",
                            Folder = "cad",
                            IsGcode = false,
                            IsJobNumber = false,
                            IsOpNumber = false,
                            IsPartNumber = true,
                            IsRevision = true,
                            IsSegment = false,
                            Name = "CAD Drawing",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("job_number");

                    b.Property<int>("PartRevId")
                        .HasColumnType("integer")
                        .HasColumnName("part_rev_id");

                    b.Property<int?>("PoLineId")
                        .HasColumnType("integer")
                        .HasColumnName("po_line_id");

                    b.Property<int>("RoutingRevId")
                        .HasColumnType("integer")
                        .HasColumnName("routing_rev_id");

                    b.Property<int?>("RunQty")
                        .HasColumnType("integer")
                        .HasColumnName("run_qty");

                    b.Property<DateOnly?>("ShipBy")
                        .HasColumnType("date")
                        .HasColumnName("ship_by");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("JobNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_job_number");

                    b.HasIndex("PartRevId")
                        .HasDatabaseName("ix_jobs_part_rev_id");

                    b.HasIndex("PoLineId")
                        .HasDatabaseName("ix_jobs_po_line_id");

                    b.HasIndex("RoutingRevId")
                        .HasDatabaseName("ix_jobs_routing_rev_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.MeasureValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DimensionId")
                        .HasColumnType("bigint")
                        .HasColumnName("dimension_id");

                    b.Property<int?>("FinalOpId")
                        .HasColumnType("integer")
                        .HasColumnName("final_op_id");

                    b.Property<int?>("GageId")
                        .HasColumnType("integer")
                        .HasColumnName("gage_id");

                    b.Property<bool>("HasNcr")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ncr");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<int?>("MeasuredBy")
                        .HasColumnType("integer")
                        .HasColumnName("measured_by");

                    b.Property<string>("NcrCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ncr_code");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("PartOpId")
                        .HasColumnType("integer")
                        .HasColumnName("part_op_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<decimal?>("Value")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_measure_values");

                    b.HasIndex("MeasuredBy")
                        .HasDatabaseName("ix_measure_values_measured_by");

                    b.HasIndex("PartOpId")
                        .HasDatabaseName("ix_measure_values_part_op_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_measure_values_product_id");

                    b.HasIndex("DimensionId", "ProductId", "MeasuredAt")
                        .HasDatabaseName("ix_measure_values_dimension_id_product_id_measured_at");

                    b.ToTable("measure_values", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_menus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_menus_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_menus_parent_id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Ncr", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("integer")
                        .HasColumnName("closed_by");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_code");

                    b.Property<long?>("MeasureValueId")
                        .HasColumnType("bigint")
                        .HasColumnName("measure_value_id");

                    b.Property<string>("NcrNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ncr_number");

                    b.Property<int?>("PartOpId")
                        .HasColumnType("integer")
                        .HasColumnName("part_op_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<int>("RaisedBy")
                        .HasColumnType("integer")
                        .HasColumnName("raised_by");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("reason_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("YearCode")
                        .HasColumnType("integer")
                        .HasColumnName("year_code");

                    b.HasKey("Id")
                        .HasName("pk_ncrs");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_ncrs_closed_by");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_ncrs_job_id");

                    b.HasIndex("NcrNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_ncrs_ncr_number");

                    b.HasIndex("PartOpId")
                        .HasDatabaseName("ix_ncrs_part_op_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_ncrs_product_id");

                    b.HasIndex("RaisedBy")
                        .HasDatabaseName("ix_ncrs_raised_by");

                    b.HasIndex("ReasonId")
                        .HasDatabaseName("ix_ncrs_reason_id");

                    b.ToTable("ncrs", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.NcrLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_at");

                    b.Property<int>("ActionBy")
                        .HasColumnType("integer")
                        .HasColumnName("action_by");

                    b.Property<long>("NcrId")
                        .HasColumnType("bigint")
                        .HasColumnName("ncr_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("pk_ncr_logs");

                    b.HasIndex("ActionBy")
                        .HasDatabaseName("ix_ncr_logs_action_by");

                    b.HasIndex("NcrId")
                        .HasDatabaseName("ix_ncr_logs_ncr_id");

                    b.ToTable("ncr_logs", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.NcrReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_ncr_reasons");

                    b.ToTable("ncr_reasons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Tool wear",
                            SortOrder = 1,
                            Tag = "TOOL"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Setup error",
                            SortOrder = 2,
                            Tag = "SETUP"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Drawing error",
                            SortOrder = 3,
                            Tag = "DRW"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Wrong material",
                            SortOrder = 4,
                            Tag = "MAT"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Machine error",
                            SortOrder = 5,
                            Tag = "MACH"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "CMM error",
                            SortOrder = 6,
                            Tag = "CMM"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Other",
                            SortOrder = 99,
                            Tag = "OTHER"
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.OpType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_op_types");

                    b.ToTable("op_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CNC",
                            Description = "CNC milling/turning",
                            Name = "CNC Machining"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INSP",
                            Description = "Quality inspection",
                            Name = "Inspection"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GRIND",
                            Description = "Surface/cylindrical grinding",
                            Name = "Grinding"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WIRE",
                            Description = "Wire electrical discharge",
                            Name = "Wire EDM"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MILL",
                            Description = "Manual milling",
                            Name = "Milling"
                        },
                        new
                        {
                            Id = 6,
                            Code = "TURN",
                            Description = "Manual turning",
                            Name = "Turning"
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("part_number");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.HasIndex("PartNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_parts_part_number");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PartOp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("ForJobOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("for_job_only");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<int?>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OpNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("op_number");

                    b.Property<decimal?>("OpNumberSort")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("op_number_sort");

                    b.Property<int?>("OpTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("op_type_id");

                    b.Property<decimal?>("ProdTime")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("prod_time");

                    b.Property<int?>("RoutingRevId")
                        .HasColumnType("integer")
                        .HasColumnName("routing_rev_id");

                    b.Property<decimal?>("SetupTime")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("setup_time");

                    b.HasKey("Id")
                        .HasName("pk_part_ops");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_part_ops_job_id");

                    b.HasIndex("OpTypeId")
                        .HasDatabaseName("ix_part_ops_op_type_id");

                    b.HasIndex("RoutingRevId")
                        .HasDatabaseName("ix_part_ops_routing_rev_id");

                    b.ToTable("part_ops", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PartRev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_released");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<int?>("ReleasedBy")
                        .HasColumnType("integer")
                        .HasColumnName("released_by");

                    b.Property<string>("RevCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rev_code");

                    b.HasKey("Id")
                        .HasName("pk_part_revs");

                    b.HasIndex("PartId", "RevCode")
                        .IsUnique()
                        .HasDatabaseName("ix_part_revs_part_id_rev_code");

                    b.ToTable("part_revs", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PoLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("PoLineNumber")
                        .HasColumnType("text")
                        .HasColumnName("po_line_number");

                    b.Property<string>("PoNumber")
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.HasKey("Id")
                        .HasName("pk_po_lines");

                    b.ToTable("po_lines", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("JobId", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_products_job_id_serial_number");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "QC Inspector"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Operator"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Planner"
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_menus");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_role_menus_menu_id");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_menus_role_id_menu_id");

                    b.ToTable("role_menus", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Routing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PartRevId")
                        .HasColumnType("integer")
                        .HasColumnName("part_rev_id");

                    b.HasKey("Id")
                        .HasName("pk_routings");

                    b.HasIndex("PartRevId")
                        .HasDatabaseName("ix_routings_part_rev_id");

                    b.ToTable("routings", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.RoutingRev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_released");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<int?>("ReleasedBy")
                        .HasColumnType("integer")
                        .HasColumnName("released_by");

                    b.Property<string>("RevCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rev_code");

                    b.Property<int>("RoutingId")
                        .HasColumnType("integer")
                        .HasColumnName("routing_id");

                    b.HasKey("Id")
                        .HasName("pk_routing_revs");

                    b.HasIndex("RoutingId", "RevCode")
                        .IsUnique()
                        .HasDatabaseName("ix_routing_revs_routing_id_rev_code");

                    b.ToTable("routing_revs", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.TechDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("file_type_id");

                    b.Property<string>("InspectNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("inspect_note");

                    b.Property<DateTimeOffset?>("InspectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspected_at");

                    b.Property<int?>("InspectorId")
                        .HasColumnType("integer")
                        .HasColumnName("inspector_id");

                    b.Property<int?>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("MachineType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("machine_type");

                    b.Property<int>("PartOpId")
                        .HasColumnType("integer")
                        .HasColumnName("part_op_id");

                    b.Property<string>("Revision")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision");

                    b.Property<string>("Segment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("segment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_tech_documents");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_tech_documents_created_by");

                    b.HasIndex("FileTypeId")
                        .HasDatabaseName("ix_tech_documents_file_type_id");

                    b.HasIndex("InspectorId")
                        .HasDatabaseName("ix_tech_documents_inspector_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_tech_documents_job_id");

                    b.HasIndex("PartOpId")
                        .HasDatabaseName("ix_tech_documents_part_op_id");

                    b.ToTable("tech_documents", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("first_login");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MesRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("mes_role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<string>("ResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reset_code");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_login");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("user_type_id");

                    b.Property<int?>("WorkStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("work_status_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_users_position_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("UserLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_login");

                    b.HasIndex("UserTypeId")
                        .HasDatabaseName("ix_users_user_type_id");

                    b.HasIndex("WorkStatusId")
                        .HasDatabaseName("ix_users_work_status_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanEnterValue")
                        .HasColumnType("boolean")
                        .HasColumnName("can_enter_value");

                    b.Property<bool>("CanRaiseNcr")
                        .HasColumnType("boolean")
                        .HasColumnName("can_raise_ncr");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_user_types");

                    b.ToTable("user_types", (string)null);
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.WorkStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsWorking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_work_statuses");

                    b.ToTable("work_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsWorking = true,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            IsWorking = false,
                            Name = "On Leave"
                        },
                        new
                        {
                            Id = 3,
                            IsWorking = false,
                            Name = "Resigned"
                        });
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Dimension", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.DimensionCategory", "Category")
                        .WithMany("Dimensions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_dimensions_dimension_categories_category_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.PartOp", "PartOp")
                        .WithMany("Dimensions")
                        .HasForeignKey("PartOpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dimensions_part_ops_part_op_id");

                    b.Navigation("Category");

                    b.Navigation("PartOp");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Job", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.PartRev", "PartRev")
                        .WithMany()
                        .HasForeignKey("PartRevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_part_revs_part_rev_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.PoLine", "PoLine")
                        .WithMany("Jobs")
                        .HasForeignKey("PoLineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_po_lines_po_line_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.RoutingRev", "RoutingRev")
                        .WithMany()
                        .HasForeignKey("RoutingRevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_routing_revs_routing_rev_id");

                    b.Navigation("PartRev");

                    b.Navigation("PoLine");

                    b.Navigation("RoutingRev");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.MeasureValue", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Dimension", "Dimension")
                        .WithMany("MeasureValues")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_measure_values_dimensions_dimension_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("MeasuredBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_measure_values_users_measured_by");

                    b.HasOne("ShopfloorManager.Domain.Entities.PartOp", "PartOp")
                        .WithMany()
                        .HasForeignKey("PartOpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measure_values_part_ops_part_op_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.Product", "Product")
                        .WithMany("MeasureValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_measure_values_products_product_id");

                    b.Navigation("Dimension");

                    b.Navigation("Inspector");

                    b.Navigation("PartOp");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Menu", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menus_menus_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Ncr", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.User", "Closer")
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ncrs_users_closed_by");

                    b.HasOne("ShopfloorManager.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ncrs_jobs_job_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.PartOp", "PartOp")
                        .WithMany()
                        .HasForeignKey("PartOpId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ncrs_part_ops_part_op_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ncrs_products_product_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.User", "Raiser")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ncrs_users_raised_by");

                    b.HasOne("ShopfloorManager.Domain.Entities.NcrReason", "Reason")
                        .WithMany("Ncrs")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ncrs_ncr_reasons_reason_id");

                    b.Navigation("Closer");

                    b.Navigation("Job");

                    b.Navigation("PartOp");

                    b.Navigation("Product");

                    b.Navigation("Raiser");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.NcrLog", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActionBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ncr_logs_users_action_by");

                    b.HasOne("ShopfloorManager.Domain.Entities.Ncr", "Ncr")
                        .WithMany("Logs")
                        .HasForeignKey("NcrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ncr_logs_ncrs_ncr_id");

                    b.Navigation("Actor");

                    b.Navigation("Ncr");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PartOp", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Job", "Job")
                        .WithMany("ForJobOnlyOps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_part_ops_jobs_job_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.OpType", "OpType")
                        .WithMany("PartOps")
                        .HasForeignKey("OpTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_part_ops_op_types_op_type_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.RoutingRev", "RoutingRev")
                        .WithMany("PartOps")
                        .HasForeignKey("RoutingRevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_part_ops_routing_revs_routing_rev_id");

                    b.Navigation("Job");

                    b.Navigation("OpType");

                    b.Navigation("RoutingRev");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PartRev", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Part", "Part")
                        .WithMany("Revisions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_part_revs_parts_part_id");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Product", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Job", "Job")
                        .WithMany("Products")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_menus_menus_menu_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_menus_roles_role_id");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Routing", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.PartRev", "PartRev")
                        .WithMany("Routings")
                        .HasForeignKey("PartRevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routings_part_revs_part_rev_id");

                    b.Navigation("PartRev");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.RoutingRev", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Routing", "Routing")
                        .WithMany("Revisions")
                        .HasForeignKey("RoutingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routing_revs_routings_routing_id");

                    b.Navigation("Routing");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.TechDocument", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tech_documents_users_created_by");

                    b.HasOne("ShopfloorManager.Domain.Entities.FileType", "FileType")
                        .WithMany("TechDocuments")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tech_documents_file_types_file_type_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tech_documents_users_inspector_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tech_documents_jobs_job_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.PartOp", "PartOp")
                        .WithMany("TechDocuments")
                        .HasForeignKey("PartOpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tech_documents_part_ops_part_op_id");

                    b.Navigation("Creator");

                    b.Navigation("FileType");

                    b.Navigation("Inspector");

                    b.Navigation("Job");

                    b.Navigation("PartOp");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.User", b =>
                {
                    b.HasOne("ShopfloorManager.Domain.Entities.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_positions_position_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_roles_role_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_user_types_user_type_id");

                    b.HasOne("ShopfloorManager.Domain.Entities.WorkStatus", "WorkStatus")
                        .WithMany("Users")
                        .HasForeignKey("WorkStatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_work_statuses_work_status_id");

                    b.Navigation("Position");

                    b.Navigation("Role");

                    b.Navigation("UserType");

                    b.Navigation("WorkStatus");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Dimension", b =>
                {
                    b.Navigation("MeasureValues");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.DimensionCategory", b =>
                {
                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.FileType", b =>
                {
                    b.Navigation("TechDocuments");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Job", b =>
                {
                    b.Navigation("ForJobOnlyOps");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Ncr", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.NcrReason", b =>
                {
                    b.Navigation("Ncrs");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.OpType", b =>
                {
                    b.Navigation("PartOps");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Part", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PartOp", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("TechDocuments");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PartRev", b =>
                {
                    b.Navigation("Routings");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.PoLine", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Product", b =>
                {
                    b.Navigation("MeasureValues");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.Routing", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.RoutingRev", b =>
                {
                    b.Navigation("PartOps");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShopfloorManager.Domain.Entities.WorkStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
