# Mosquitto MQTT Broker — Development config
listener 1883
allow_anonymous true

# WebSocket (cho test từ browser)
listener 9002
protocol websockets
allow_anonymous true

persistence false
log_dest stdout
log_type all
